name: snowflake_s3_demo
version: 1.0.0
config-version: 2

profile: snowflake_s3_demo

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  snowflake_s3_demo:
    staging:
      +materialized: view
