version: 2

sources:
  - name: raw
    database: "{{ target.database }}"
    schema: RAW
    tables:
      - name: events_raw

models:
  - name: stg_events
    description: "Staged events from the raw Snowflake table."
